image:
  registry: ghcr.io
  repository: felixhir/ticket-generator
  tag: 8ca50b494450d345fffdb8ce68ca3a9415bdd8c8
  pullPolicy: IfNotPresent
istioRouting:
  enabled: true
  domain: ticket-generator.scholl.tech
certificate:
  enabled: true
  namespace: istio-system
  issuerName: letsencrypt
  issuerKind: ClusterIssuer
secretEnv:
  - name: ALTCHA_HMAC_SECRET
    existingSecret: ticket-generator
  - name: TICKETMASTER_API_KEY
    existingSecret: ticket-generator
