image:
  registry: ghcr.io
  repository: felixhir/ticket-generator
  tag: 4059126e17c7c1bbc4aa3a7d262205e7bf5f5bdd
  pullPolicy: IfNotPresent

istioRouting:
  enabled: true
  domain: ticket-generator.scholl.tech

certificate:
  enabled: true
  namespace: istio-system
  issuerName: letsencrypt
  issuerKind: ClusterIssuer

secretEnv:
  - name: ALTCHA_HMAC_SECRET
    existingSecret: ticket-generator
  - name: TICKETMASTER_API_KEY
    existingSecret: ticket-generator
