image:
  registry: ghcr.io
  repository: felixhir/ticket-generator
  tag: 7f372252c0a361edfdc69b0a544acde05688b7a7
  pullPolicy: IfNotPresent

istioRouting:
  enabled: true
  domain: ticket-generator.scholl.tech

certificate:
  enabled: true
  namespace: istio-system
  issuerName: letsencrypt-prod
  issuerKind: ClusterIssuer
