replicaCount: 1
image:
  registry: ghcr.io
  repository: felixhir/ticket-generator
  tag: eb8ad7346a80b7dec06252f1f5e003885987ae49
  pullPolicy: IfNotPresent
  pullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
service:
  type: ClusterIP
  port: 80
  targetPort: http
containerPort: 3000
resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
revisionHistoryLimit: 3
livenessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
nodeSelector: {}
tolerations: []
affinity: {}
app:
  buildVersion: ""
env: []
extraEnvFrom: []
istioRouting:
  enabled: false
  domain: ""
  gateway:
    selector:
      app: istio-ingress
  acmeChallenge:
    host: acme-solver.istio-system.svc.cluster.local
    port: 8089
  httpsRedirect: true
certificate:
  enabled: false
  namespace: istio-system
  dnsNames: []
  issuerName: ""
  issuerKind: ClusterIssuer
  includeWwwSan: false
