version: 2
updates:
    # Node.js
    - package-ecosystem: 'npm'
      directory: '.'
      target-branch: master
      schedule:
          interval: 'weekly'
      assignees:
          - 'felixhir'
      groups:
          all:
              patterns:
                  - '*'
